[general]
import = [
	# "~/.config/alacritty/themes/gruvbox-dark.toml"
	"~/.cache/wal/colors-alacritty.toml"
]

[mouse]
hide_when_typing = false
bindings = [{ action = "None", mouse = "Middle" }]

[scrolling]
history = 100000

[window]
option_as_alt = "Both"
opacity = 0.98

[bell]
animation = "EaseOutSine"
color = "#cc241d"
duration = 150
command = { program = "xkbbell" }

[font]
size = 12.0
bold = { family = "Iosevka Term Nerd Font Mono", style = "Bold" }
bold_italic = { family = "Iosevka Term Nerd Font Mono", style = "Bold Italic" }
italic = { family = "Iosevka Term Nerd Font Mono", style = "Italic" }
normal = { family = "Iosevka Term Nerd Font Mono", style = "Regular" }
builtin_box_drawing = false
offset = { x = 1, y = 2 }

[env]
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
TERM = "xterm-256color"

[keyboard]
bindings = [
	{ chars = "\u001B[27;3;9~", key = "Tab", mods = "Alt" },
	{ chars = "\u001B[27;4;9~", key = "Tab", mods = "Alt|Shift" },
	{ chars = "\u001B[27;5;9~", key = "Tab", mods = "Control" },
	{ chars = "\u001B[27;6;9~", key = "Tab", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;72~", key = "H", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;74~", key = "J", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;75~", key = "K", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;76~", key = "L", mods = "Control|Shift" },
	{ chars = "\u001B[27;5;49~", key = "Key1", mods = "Control" },
	{ chars = "\u001B[27;5;50~", key = "Key2", mods = "Control" },
	{ chars = "\u001B[27;5;51~", key = "Key3", mods = "Control" },
	{ chars = "\u001B[27;5;52~", key = "Key4", mods = "Control" },
	{ chars = "\u001B[27;5;53~", key = "Key5", mods = "Control" },
	{ chars = "\u001B[27;5;54~", key = "Key6", mods = "Control" },
	{ chars = "\u001B[27;5;55~", key = "Key7", mods = "Control" },
	{ chars = "\u001B[27;5;56~", key = "Key8", mods = "Control" },
	{ chars = "\u001B[27;5;57~", key = "Key9", mods = "Control" },
	# { chars = "\u001B[27;5;58~", key = "Key0", mods = "Control" },
]
