[mouse]
hide_when_typing = false
bindings = [{ action = "None", mouse = "Middle" }]

[scrolling]
history = 100000

[window]
option_as_alt = "Both"

[bell]
animation = "EaseOutSine"
color = "#cc241d"
duration = 150
command = { program = "xkbbell" }

[font]
size = 12.0
bold = { family = "ComicCodeLigatures Nerd Font", style = "Bold" }
bold_italic = { family = "ComicCodeLigatures Nerd Font", style = "Bold Italic" }
italic = { family = "ComicCodeLigatures Nerd Font", style = "Italic" }
normal = { family = "ComicCodeLigatures Nerd Font", style = "Regular" }
builtin_box_drawing = false

[env]
# https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[keyboard]
bindings = [
	{ chars = "\u001B[27;3;9~", key = "Tab", mods = "Alt" },
	{ chars = "\u001B[27;4;9~", key = "Tab", mods = "Alt|Shift" },
	{ chars = "\u001B[27;5;9~", key = "Tab", mods = "Control" },
	{ chars = "\u001B[27;6;9~", key = "Tab", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;72~", key = "H", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;74~", key = "J", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;75~", key = "K", mods = "Control|Shift" },
	{ chars = "\u001B[27;6;76~", key = "L", mods = "Control|Shift" },
	{ chars = "\u001B[27;5;49~", key = "Key1", mods = "Control" },
	{ chars = "\u001B[27;5;50~", key = "Key2", mods = "Control" },
	{ chars = "\u001B[27;5;51~", key = "Key3", mods = "Control" },
	{ chars = "\u001B[27;5;52~", key = "Key4", mods = "Control" },
	{ chars = "\u001B[27;5;53~", key = "Key5", mods = "Control" },
	{ chars = "\u001B[27;5;54~", key = "Key6", mods = "Control" },
	{ chars = "\u001B[27;5;55~", key = "Key7", mods = "Control" },
	{ chars = "\u001B[27;5;56~", key = "Key8", mods = "Control" },
	{ chars = "\u001B[27;5;57~", key = "Key9", mods = "Control" },
	# { chars = "\u001B[27;5;58~", key = "Key0", mods = "Control" },
]
