[bell]
animation = "Ease"
color = "#cc241d"
duration = 300

[bell.command]
program = "xkbbell"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "ComicCodeLigatures Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicCodeLigatures Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicCodeLigatures Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCodeLigatures Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001B[27;3;9~"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[27;4;9~"
key = "Tab"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;72~"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;74~"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;75~"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;6;76~"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;49~"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;50~"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;51~"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;52~"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;53~"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;54~"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;55~"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;56~"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;57~"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;58~"
key = "Key0"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[scrolling]
history = 100000

[window]
dynamic_padding = true
dynamic_title = true
