-- require('kirk.settings')
require('kirk.treesitter')
require('kirk.lsp.lsp')
require('kirk.snippets.snippets')
require('kirk.telescope')
require('kirk.comment')
require('kirk.harpoon')
require('kirk.indent')
require('kirk.tree')
require('kirk.barbar')
require('kirk.alpha')
-- require('kirk.scrollbar')
-- require('kirk.neoscroll')

require('lualine').setup()
