-- require('kirk.settings')
require('kirk.auto_session')
require('kirk.lualine')
require('kirk.treesitter')
require('kirk.lsp.lsp')
require('kirk.snippets.snippets')
require('kirk.telescope')
require('kirk.comment')
require('kirk.harpoon')
require('kirk.indent')
require('kirk.tree')
require('kirk.barbar')
require('kirk.alpha')
require('kirk.scrollbar')
require('kirk.neoscroll')
-- require('kirk.colorizer') -- TODO: figure out why this doesn't work
