---
services:
  stylua:
    container_name: stylua
    image: johnnymorganz/stylua:2.5.2
    volumes:
      - ./:/data:ro

  yamllint:
    container_name: yamllint
    image: registry.gitlab.com/pipeline-components/yamllint:v0.35.16
    volumes:
      - ./:/code:ro

  markdownlint:
    container_name: markdownlint
    image: registry.gitlab.com/pipeline-components/markdownlint:v0.14.9
    volumes:
      - ./:/code:ro
