set number relativenumber				" turn hybrid line numbers on
set cursorline						" highlight current line

set incsearch						" highlight matches as you type
set hlsearch						" highlight matches once a search is complete
nnoremap <leader><space> :nohlsearch<CR>		" turn off search highlight

set autoindent						" new lines inherit the indentation of previous lines.
set linebreak						" avoid wrapping a line in the middle of a word

set foldenable						" enable folding
set foldlevelstart=10					" open most folds by default
set foldnestmax=10					" 10 nested fold max
nnoremap <space> za					" space open/closes folds
set foldmethod=indent					" fold based on indent level

syntax enable						" enable syntax highlighting
set showmatch						" highlight matching [{()}]

set tabstop=4						" number of visual spaces per TAB
set softtabstop=4					" number of spaces in tab when editing
filetype indent on					" load filetype-specific indent files

set laststatus=2					" always display the status bar

set mouse=a						" enable mouse for scrolling and resizing

set spell						" enable spellchecking

colorscheme badwolf					" awesome colorscheme

set wildmenu						" visual autocomplete for command menu

"set lazyredraw						" redraw only when we need to.

nnoremap j gj						" move vertically by visual line
nnoremap k gk						" move vertically by visual line


""" Leader shortcuts
let mapleader=","					" leader is comma

inoremap jk <esc>" jk is escap				" jk is escape
