let mapleader=","					" leader is comma
nnoremap <leader>ve :e $MYVIMRC<CR>
nnoremap <leader>vr :so $MYVIMRC<CR>

set number relativenumber				" turn hybrid line numbers on
set cursorline						" highlight current line
set termguicolors

set incsearch						" highlight matches as you type
set hlsearch						" highlight matches once a search is complete
set nohlsearch						" turn off search highlight

set autoindent						" new lines inherit the indentation of previous lines.
set nowrap							" don't wrap lines
set linebreak						" avoid wrapping a line in the middle of a word

set foldenable						" enable folding
set foldlevelstart=10					" open most folds by default
set foldnestmax=10					" 10 nested fold max
nnoremap <space> za					" space open/closes folds
set foldmethod=indent					" fold based on indent level

syntax enable						" enable syntax highlighting
set showmatch						" highlight matching [{()}]

set scrolloff=8						" scroll when x away from edge
set signcolumn=yes					" column for linting
set colorcolumn=80					" 80col limit

set tabstop=4						" number of visual spaces per TAB
set softtabstop=4					" number of spaces in tab when editing
set shiftwidth=4					" number of spaces when indenting with <>
filetype indent on					" load filetype-specific indent files

set laststatus=2					" always display the status bar

set mouse=a						" enable mouse for scrolling and resizing

" set spell						" enable spellchecking

set wildmenu						" visual autocomplete for command menu

augroup WrapLineInLatexFile
	autocmd!
	autocmd FileType tex setlocal wrap
augroup END

augroup WrapLineInMarkdownFile
	autocmd!
	autocmd FileType markdown setlocal wrap
augroup END

"set lazyredraw						" redraw only when we need to.

set exrc							" use local vimrc, if it exists

" nnoremap j gj						" move vertically by visual line
" nnoremap k gk						" move vertically by visual line

" ThePrimeagen remappings
" 'Y' to behave like other capitals
nnoremap Y $y

" easier navigation
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap J mzJ`z

" easier undos
inoremap , ,<c-g>u
inoremap . .<c-g>u
inoremap [ [<c-g>u
inoremap ! !<c-g>u
inoremap ? ?<c-g>u

" add large enough relative jumps to jump list
nnoremap <expr> j (v:count > 5 ? "m'" . v:count : "") . 'gj'
nnoremap <expr> k (v:count > 5 ? "m'" . v:count : "") . 'gk'

" move text
vnoremap <A-j>  :m '>+1<CR>gv=gv
vnoremap <A-k>  :m '<-2<CR>gv=gv
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k>  :m .-2<CR>==

" re-select the selection after indenting
vnoremap < <gv
vnoremap > >gv

" Build if a note file
autocmd BufwritePost *note-*.md silent !~/scripts/build_notes.sh %:p

" remove trailing whitespace on each save
autocmd BufWritePre * :%s/\s\+$//e

" use relative numbers only in active buffer
augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

" transparent background
au ColorScheme * hi Normal ctermbg=none guibg=none

" comments in jsonc
autocmd FileType json syntax match Comment +\/\/.\+$+

""" Leader shortcuts

inoremap jk <esc>" jk is escap				" jk is escape

set completeopt=menu,menuone,noselect
