---
name: "nvim"

on: ["push"]

env:
  NVIM_BASE_DIR: "vim/.config/nvim"
  STYLUA_BASE_DIR: "formatters/.config/stylua"

jobs:
  stylua:
    runs-on: docker
    container:
      image: node:26-trixie-slim # needed for actions/checkout
    steps:
      - run: apt update && apt install -y curl git # needed for installing homebrew
      - name: "Install Homebrew"
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $FORGEJO_PATH
      - uses: actions/checkout@v7
      - run: brew install stylua
      - name: "Run stylua"
        run: stylua --allow-hidden --check -f ${{ env.STYLUA_BASE_DIR }}/stylua.toml ${{ env.NVIM_BASE_DIR }}
