---
name: "nvim"

on: ["push"]

env:
  NVIM_BASE_DIR: "vim/.config/nvim"
  STYLUA_BASE_DIR: "formatters/.config/stylua"

jobs:
  stylua:
    runs-on: docker
    container:
      image: node:26-trixie
    steps:
      - run: apt update && apt install -y stow cargo
      - uses: actions/checkout@v6
      - run: cargo install stylua
      - name: "Run stylua"
        run: stylua --allow-hidden --check -f ${{ env.STYLUA_BASE_DIR }}/stylua.toml ${{ env.NVIM_BASE_DIR }}
