---
name: "nvim"

on: ["push"]

env:
  NVIM_BASE_DIR: "vim/.config/nvim"
  STYLUA_BASE_DIR: "formatters/.config/stylua"

jobs:
  stylua:
    runs-on: docker
    container:
      image: node:26-trixie-slim # needed for actions/checkout
    steps:
      - uses: actions/checkout@v6
      - name: Clone External stylue-action
        run: |
          git clone https://github.com/JohnnyMorganz/stylua-action.git .github/actions/style-action
          cd .github/actions/stylua-action && git checkout v5.0.0
      - name: "Run stylua"
        uses: ./.github/actions/stylua-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.5.2
          args: --allow-hidden --check -f ${{ env.STYLUA_BASE_DIR }}/stylua.toml ${{ env.NVIM_BASE_DIR }}
