name: "qtile"

on: ["push"]

jobs:
  config-check:
    runs-on: docker
    container:
      image: debian:12-slim
    steps:
      - name: "Install node"
        run: apt update && apt upgrade && apt install -y lsb-release nodejs
      - uses: actions/checkout@v6
      - name: "Install qtile"
        run: apt install qtile
      - name: "Validate"
        run: qtile check --config ./window-managers/.config/qtile/config.py
