name: "qtile"

on: ["push"]

jobs:
  check:
    runs-on: docker
    container:
      image: python:3.14.3-slim
    steps:
      - uses: actions/checkout@v6
      - name: "Install qtile"
        run: pip install qtile==0.35.0
      - name: "Validate"
        run: qtile check --config ./window-managers/.config/qtile/config.py
