---
name: smoke-test

on: [push]

jobs:
  install:
    runs-on: docker
    container:
      image: node:26-trixie-slim # needed for actions/checkout
    steps:
      - uses: actions/checkout@v7
      - run: apt update && apt install -y stow make
      - run: make install
