name: smoke-test

on: [push]

jobs:
  install:
    runs-on: docker
    container:
      image: debian:12-slim
    steps:
      - name: "Install node"
        run: apt update && apt install -y lsb-release nodejs

      - uses: actions/checkout@v6

      - name: Install stow
        run: apt-get install -y stow

      - name: Run install script
        run: ./install.sh
