name: smoke-test

on: [push]

jobs:
  install-check:
    runs-on: docker
    container:
      image: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian:12-slim
          - sickcodes/docker-osx
    steps:
      - name: "Install node (linux)"
        run: apt update && apt install -y lsb-release nodejs
        if: ${{ matrix.os == 'debian:12-slim' }}

      - name: "Install Homebrew (macos)"
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $FORGEJO_PATH
        if: ${{ matrix.os == 'sickcodes/docker-osx' }}

      - name: Install node (macos)
        run: brew install nodejs
        if: ${{ matrix.os == 'sickcodes/docker-osx' }}

      - uses: actions/checkout@v6

      - name: Install stow (linux)
        run: apt-get install -y stow
        if: ${{ matrix.os == 'debian:12-slim' }}

      # - name: Install stow (macos)
      #   run: brew install stow
      #   if: ${{ matrix.os == 'sickcodes/docker-osx' }}

      - name: Run install script
        run: ./install.sh
