name: "zsh"
on: ["push"]

jobs:
  test:
    runs-on: docker
    container:
      image: ubuntu:24.04
    steps:
      - name: "Install node"
        run: apt update && apt install -y lsb-release nodejs
      - uses: "actions/checkout@v6"
      - run: "apt install -y stow"
      - run: "stow shell"

      - run: "apt install -y zsh"
      - name: "Check zsh"
        run: "ZDOTDIR=~/.config/zsh zsh --version"
