---
prSections:
  - title: Created
    filters: is:open author:@me
  - title: Needs review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me

issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open -author:@me

defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

repoPaths:
  :owner/:repo: ~/dev/pulls/:owner/:repo
  reMarkable/*: ~/dev/remarkable/*

  # TODO: add bindings for using git-worktree
keybindings:
  issues: []
  prs:
    - key: i
      command: |
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen main...{{.HeadRefName}}"
        '

theme:
  ui:
    table:
      showSeparator: true
  colors: # these render differently in tmux
    background:
      selected: "#1D2021" # bg0_h
    border:
      faint: "#928374" # gray
      primary: "#458588" # blue
      secondary: "#3C3836" # bg1
    text:
      faint: "#A89984" # fg4
      inverted: "#32303F" # bg0_s
      primary: "#EBDBB2" # fg
      secondary: "#A89984" # fg4
      success: "#B8BB26" # green
      warning: "#FB4934" # red
