# https://posting.sh/guide/configuration/

theme: gruvbox
load_user_themes: false
layout: vertical

watch_env_files: false
watch_themes: false

animation: basic

spacing: compact

pager: bat
pager_json: bat
editor: nvim
