return {
  "tpope/vim-fugitive",
  enabled = false,
  lazy = false,
  cmd = {
    "G",
    "GBrowse",
    "GDelete",
    "GMove",
    "GRemove",
    "GRename",
    "Gclog",
    "Gdiffsplit",
    "Gedit",
    "Ggrep",
    "Ghdiffsplit",
    "Git",
    "Gread",
    "Gsplit",
    "Gvdiffsplit",
    "Gwrite",
  },
  -- keys = {
  --   {
  --     "<leader>gg",
  --     vim.cmd.Git,
  --     desc = "Show git-fugitive UI",
  --   },
  -- },
}
