[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#fbf1c7"
foreground = "#3c3836"

[colors.normal]
black = "#fbf1c7"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#7c6f64"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#d3869b"
red = "#9d0006"
white = "#3c3836"
yellow = "#b57614"
