return {
  "jay-babu/mason-null-ls.nvim",
  enabled = false,
  cond = not vim.g.started_by_firenvim,
  dependencies = {
    "williamboman/mason.nvim",
    "jose-elias-alvarez/null-ls.nvim",
  },
  event = "UIEnter",
  cmd = {
    "NullLsInstall",
    "NullLsUninstall",
  },
  opts = {
    automatic_installation = true,
    automatic_setup = true,
    ensure_installed = {
      "actionlint",
      "ansiblelint",
      "autopep8",
      "buf",
      "commitlint",
      "dotenv_linter",
      "editorconfig-checker",
      "eslint_d",
      "flake8",
      "gofumpt",
      "goimports",
      "gomodifytags",
      "hadolint",
      -- "markdownlint",
      -- "ocamlformat",
      "prettier",
      "proselint",
      "protoc_gen_lint",
      "pylint",
      "staticcheck",
      "stylelint",
      "stylua",
      "terraform_validate",
      "tfsec",
      "trail_space",
      -- "black",
    },
  },
}
