format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$sudo\
$cmd_duration\
$jobs\
$status\
$shell\
$character
"""

continuation_prompt = "▶▶  "

[line_break]
disabled = true

