#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Configuration

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# tiling options
yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config split_type auto

# padding and gaps
yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 15

# split ratios
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# mouse support
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_drop_action swap

# window borders
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config window_border_width 4
yabai -m config window_border_radius 12
yabai -m config window_border_blur off
yabai -m config window_border_hidpi on
yabai -m config window_border off

# window modifications
yabai -m config window_topmost on
yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_origin_display default
yabai -m config window_animation_duration 0.0
yabai -m config window_opacity_duration 0.0

# status bar
# TODO: configure ubersicht
# yabai -m config external_bar main:20:0
# yabai -m config external_bar all:20:20

# global settings
yabai -m config insert_feedback_color 0xffd75f5f

# enable debug logging
yabai -m config debug_output on

# windows to ignore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off

echo "yabai configuration loaded.."
