return {
	'williamboman/mason-lspconfig.nvim',
	event = "VeryLazy",
	dependencies = {
		'williamboman/mason.nvim',
	},
	opts = {
		automatic_installation = true,
		ensure_installed = {
			"ansiblels",
			"bashls",
			"clangd",
			"cmake",
			"cssls",
			"cssmodules_ls",
			"diagnosticls",
			"docker_compose_language_service",
			"dockerls",
			"eslint",
			"golangci_lint_ls",
			"gopls",
			"html",
			"jsonls",
			"kotlin_language_server",
			"lemminx",
			"lua_ls",
			"marksman",
			"pyright",
			"rnix",
			"rust_analyzer",
			"sqlls",
			"taplo",
			"texlab",
			"tsserver",
			"vimls",
			"yamlls",
		},
	},
}
