return {
	"williamboman/mason-lspconfig.nvim",
	cond = not vim.g.started_by_firenvim,
	event = "VeryLazy",
	dependencies = {
		"williamboman/mason.nvim",
	},
	cmd = {
		"LspInstall",
		"LspUninstall",
	},
	opts = {
		ensure_installed = {
			"angularls",
			"ansiblels",
			"asm_lsp",
			"azure_pipelines_ls",
			"bashls",
			"clangd",
			"clojure_lsp",
			"cmake",
			"csharp_ls",
			"cssls",
			"cssmodules_ls",
			"denols",
			"diagnosticls",
			"docker_compose_language_service",
			"dockerls",
			"eslint",
			"fennel_language_server",
			"fsautocomplete",
			"golangci_lint_ls", -- TODO: figure out why this doesnt work
			"gopls",
			"gradle_ls",
			"hls",
			"html",
			"jdtls",
			"jsonls",
			"kotlin_language_server",
			"lemminx",
			"lua_ls",
			"ocamllsp",
			"omnisharp",
			"pyright",
			"rust_analyzer",
			"sqlls",
			"taplo",
			"terraformls",
			"texlab",
			"tflint",
			"tsserver",
			"vimls",
			"yamlls",
			"zls",
			-- "rnix",
		},
	},
}
