return {
	"jay-babu/mason-null-ls.nvim",
	dependencies = {
		"williamboman/mason.nvim",
		"jose-elias-alvarez/null-ls.nvim",
	},
	event = "VeryLazy",
	opts = {
		automatic_installation = true,
		automatic_setup = true,
		ensure_installed = {
			"autopep8",
			"black",
			"buf",
			"commitlint",
			"eslint_d",
			"flake8",
			"gofumpt",
			"hadolint",
			"markdownlint",
			"prettier",
			"proselint",
			"protoc_gen_lint",
			"pylint",
			"stylelint",
			"stylua",
			"terraform_validate",
			"tfsec",
		},
	},
}
