vim.cmd([[let g:enable_spelunker_vim = 1]])
vim.cmd([[let g:enable_spelunker_vim_on_readonly = 1]])
vim.cmd([[let g:spelunker_check_type = 2]])
vim.cmd([[let g:spelunker_highlight_type = 1]])
vim.cmd([[let g:spelunker_spell_bad_group = 'SpelunkerSpellBad']])
vim.cmd([[let g:spelunker_complex_or_compound_word_group = 'SpelunkerComplexOrCompoundWord']])
vim.cmd([[highlight SpelunkerSpellBad cterm=underline ctermfg=247 gui=undercurl guifg=NONE]])
vim.cmd([[highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=NONE gui=undercurl guifg=NONE]])
