name: github-to-codeberg-sync
on:
  push:
    branches:
      - "**"
      # TODO: re-renable cron _after_ testing is done
      # workflow_dispatch: # Manual dispatch
      # schedule:
      #   - cron: "0 */6 * * *"

jobs:
  sync-repo-to-forgejo:
    environment: codeberg-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "${{ vars.FORGEJO_BASE_URL }}/${{ vars.FORGEJO_USERNAME }}/${{ vars.FORGEJO_REPO }}.git"
          GIT_SSH_PUBLIC_KEY: "${{ secrets.GIT_SSH_PUBLIC_KEY }}"
          GIT_SSH_PRIVATE_KEY: "${{ secrets.GIT_SSH_PRIVATE_KEY }}"
          GIT_SSH_KNOWN_HOSTS: "${{ secrets.GIT_SSH_KNOWN_HOSTS }}"
