---
name: "nvim"

on: ["push"]

# TODO: get this to work
env:
  NVIM_BASE_DIR: "nvim/.config/nvim"

jobs:

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0
          args: >-
            --allow-hidden
            --check
            -f nvim/.config/nvim/stylua.toml
            nvim/.config/nvim

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MunifTanjim/setup-neovim-action@v1
      - run: nvim -u nvim/.config/nvim/init.lua
