---
name: "nvim"

on: ["push"]

env:
  NVIM_BASE_DIR: "vim/.config/nvim"
  STYLUA_BASE_DIR: "formatters/.config/stylua"

jobs:
  stylua:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.4.0
          args: >-
            --allow-hidden --check -f ${{ envSTYLUA_BASE_DIR }}/stylua.toml ${{ env.NVIM_BASE_DIR }}
