name: "qtile"

on: ["push"]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: "Install qtile"
        run: pip install qtile==0.35.0
      - name: "Validate"
        run: qtile check --config ./window-managers/.config/qtile/config.py
