name: "qtile"

on: ["push"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: "Install qtile dependencies"
        run: sudo apt install -y python3-pip python3-xcffib python3-cairocffi
      - name: "Install qtile"
        run: pip install qtile
      - name: "Validate"
        run: qtile check --config ./qtile/.config/qtile/.config.py
