name: "qtile"

on: ["push"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - name: "Install qtile"
        run: pip install qtile
      - name: "Validate"
        run: qtile check --config ./window-managers/.config/qtile/config.py
