name: "qtile"

on: ["push"]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install qtile"
        run: sudo apt install -y qtile
      - name: "Validate"
        run: qtile check --config ./qtile/.config/qtile/.config.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "sudo apt install stow"
      - run: "stow nvim"
      - uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly
      - name: Test nvim with config
        run: nvim --headless +qa
