name: "qtile"

on: ["push"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install qtile"
        run: sudo apt install -y qtile
      - name: "Validate"
        run: qtile check --config ./qtile/.config/qtile/.config.py
