---
name: secrets
on: [push]
env:
  SCANNER_ARGS: |
    --exclude-files 'nvim/.config/nvim/lazy-lock.json'

jobs:

  check-secrets:
    name: Check for secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Secret scanner
        uses: secret-scanner/action@0.2.1
        with:
          detect_secrets_version: 1.4.0
          python_version: 3.11.8
          detect_secret_additional_args: ${{ env.SCANNER_ARGS }}
