---
name: Secrets
on: [push]

jobs:

  check-secrets:
    name: Check for secrets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Secret scanner
        uses: secret-scanner/action@0.2.1
