---
name: smoke-test

on: [push]

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install stow (linux)
        run: sudo apt-get install -y stow
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - uses: Homebrew/actions/setup-homebrew@master
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install stow (macos)
        run: brew install stow
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Run install script
        run: ./install.sh
