---
name: smoke-test

on: [push]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        # firefox:
        #   - "latest-beta"
        #   - "latest-devedition"
        #   - "latest-nightly"
        #   - "latest-esr"
        #   - "latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install stow and firefox (linux)
        run: sudo apt-get install -y stow firefox
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - uses: Homebrew/actions/setup-homebrew@master
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install stow and firefox (macos)
        run: brew install stow firefox
        if: ${{ matrix.os == 'macos-latest' }}

      # - name: Setup firefox (${{ matrix.firefox }})
      #   uses: browser-actions/setup-firefox@v1
      #   with:
      #     firefox-version: ${{ matrix.firefox }}

      - name: Run install script
        run: ./install.sh
