---
name: smoke-test

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stow
        run: sudo apt-get install -y stow

      - name: Run install script
        run: ./install.sh
