---
name: smoke-test

on: [push]

jobs:

  tests-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y stow

      - name: Run install script
        run: ./install.sh

  tests-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew stow

      - name: Run install script
        run: ./install.sh
