name: "zsh"
on: ["push"]

jobs:
  test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - uses: "actions/checkout@v6"
      - run: "apt install -y stow"
      - run: "stow shell"

      - run: "apt install -y zsh"
      - name: "Check zsh"
        run: "ZDOTDIR=~/.config/zsh zsh --version"
